<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankAccounts.AppplicationData\BankAccounts.AppplicationData.csproj" />
    <ProjectReference Include="..\BankAccounts.Shared\BankAccounts.Shared.csproj" />
    <ProjectReference Include="..\HttpClientApp\HttpClientApp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.9.0" />
    <PackageReference Include="Testcontainers.Redis" Version="4.9.0" />
  </ItemGroup>

</Project>
