name: ci-cqrs

on:
  push:
    branches: ["CQRS"]
  pull_request:
    branches: ["CQRS"]
  workflow_dispatch:

concurrency:
  group: ci-cqrs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: .NET + Docker + Tests
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell

    env:
      DOTNET_NOLOGO: "true"
      DOTNET_CLI_TELEMETRY_OPTOUT: "true"
      CONFIGURATION: Release
      SOLUTION: BankAccounts.sln
      # ЯВНО указываем Windows pipe — критично для Docker
